require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Gmail SMTP로 실제 이메일 발송
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: "smtp.gmail.com",
    port: 587,
    domain: "gmail.com",
    user_name: Rails.application.credentials.dig(:gmail, :user_name),
    password: Rails.application.credentials.dig(:gmail, :password),
    authentication: "plain",
    enable_starttls_auto: true
  }
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Action Controller/Active Storage URL 생성 시 호스트 설정
  # Turbo Stream 브로드캐스트 시 request 객체가 없어서 필요함
  config.action_controller.default_url_options = { host: "localhost", port: 3000 }

  # OAuth 세션 쿠키 설정: IPv4/IPv6 혼용 문제 해결
  # Google OAuth 콜백이 ::1(IPv6)로 돌아올 때 127.0.0.1(IPv4) 세션과 불일치하는 문제 방지
  config.session_store :cookie_store,
    key: "_startup_community_session",
    domain: :all,  # 모든 서브도메인/IP에서 쿠키 공유
    same_site: :lax

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # localhost와 127.0.0.1 모두 허용
  config.hosts << "localhost"
  config.hosts << "127.0.0.1"
  config.hosts << /.*\.localhost/  # 서브도메인도 허용

  # Action Cable도 localhost와 127.0.0.1 모두 허용
  config.action_cable.allowed_request_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    %r{http://localhost:\d+},
    %r{http://127\.0\.0\.1:\d+}
  ]

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Bullet: N+1 쿼리 탐지 설정 (2026-01-18)
  config.after_initialize do
    Bullet.enable = true
    Bullet.alert = false         # 브라우저 alert 비활성화 (로그는 유지)
    Bullet.bullet_logger = true  # log/bullet.log에 기록
    Bullet.console = true        # 브라우저 콘솔에 출력
    Bullet.add_footer = true     # 페이지 하단에 정보 표시
    Bullet.rails_logger = true   # Rails 로그에 출력

    # Whitelist: 조건부 AVOID 경고 무시 (2026-01-18)
    # avatar가 조건부로 사용됨 (anonymous/external URL/fallback 시 미사용)
    Bullet.add_safelist(type: :unused_eager_loading, class_name: "User", association: :avatar_attachment)
    Bullet.add_safelist(type: :unused_eager_loading, class_name: "ActiveStorage::Attachment", association: :blob)
    # likes가 조건부로 사용됨 (좋아요 수 미표시 시 미사용)
    Bullet.add_safelist(type: :unused_eager_loading, class_name: "Comment", association: :likes)
    # sender가 조건부로 사용됨 (시스템 메시지 시 미사용)
    Bullet.add_safelist(type: :unused_eager_loading, class_name: "Message", association: :sender)
  end
end
